Repository brazier-dev/hikari-flare, pull requests merged in 2022-10, with the labels that each got.

#20 Implement Context
  flare/context.py
  flare/internal/event_handler.py
Labels: enhancement

#26 Add sphinx documentation
  .gitignore
  .readthedocs.yml
  doc_requirements.txt
  docs/source/api_reference.rst
  docs/source/api_references/button.rst
  docs/source/api_references/component.rst
  docs/source/api_references/context.rst
  docs/source/api_references/converters.rst
  docs/source/api_references/exceptions.rst
  docs/source/api_references/internal/event_handler.rst
  docs/source/api_references/internal/serde.rst
  docs/source/api_references/internals.rst
  docs/source/api_references/select.rst
  docs/source/changelog.rst
  docs/source/changelogs/v0.rst
  docs/source/conf.py
  docs/source/getting-started.rst
  docs/source/guide.rst
  docs/source/guides/converters.rst
  docs/source/guides/editing.rst
  docs/source/guides/state.rst
  docs/source/index.rst
  flare/converters.py
  noxfile.py
  setup.py
Labels: documentation

#28 Update readme example
  README.md
Labels: documentation

#29 Fix button label & emoji not being optional
  flare/components/button.py
  flare/components/select.py
Labels: bug

#32 Fix deserializing Unions
  flare/converters.py
Labels: bug

#31 Add BoolConverter
  flare/converters.py
Labels: enhancement

#27 Add custom serde support
  flare/components/base.py
  flare/exceptions.py
  flare/internal/README.md
  flare/internal/event_handler.py
  flare/internal/serde.py
Labels: enhancement

#38 Hash default cookie
  flare/components/base.py
Labels: enhancement

#60 Add CLI
  flare/__main__.py
  setup.py
Labels: enhancement

#61 Add short-hand method overload for defer
  docs/source/api_reference.md
  docs/source/changelog.md
  flare/context.py
Labels: enhancement
